In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from IPython.display import display

# Kết nối tới PostgreSQL
engine = create_engine('postgresql+psycopg2://airflow:airflow@localhost:5434/airflow')

# Đọc bảng customers từ schema  retails_data
df = pd.read_sql('SELECT * FROM retails_data.customers', engine)

# Kích thước dataframe
print("Shape:", df.shape)

# Tỉ lệ thiếu dữ liệu
print("\nMissing values per column:")
print(df.isnull().sum())

Shape: (1000, 8)

Missing values per column:
customer_id              0
name                     0
email                    0
phone                    0
loyalty_program_id       0
gender                   0
age                   1000
created_at            1000
dtype: int64

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

# Kết nối tới PostgreSQL
engine = create_engine('postgresql+psycopg2://airflow:airflow@localhost:5434/airflow')

# Danh sách bảng
tables = [
    'brands', 'categories', 'loyalty_programs', 'suppliers', 'products',
    'stores', 'employees', 'payments', 'sales_transactions', 'sales_items', 'inventory',
    'stock_movements', 'purchase_orders', 'shipments', 'returns', 'promotions',
    'campaigns', 'customer_feedback', 'store_visits', 'pricing_history', 'discount_rules',
    'tax_rules'
]

# Schema nếu cần (ví dụ: raw_retails_data)
schema = '_invalid_data'

# Danh sách kết quả
results = []

# customers_df = pd.read_sql(f'SELECT customer_id, name, email, phone, loyalty_program_id, created_at FROM snapshots.snapshot_customers', engine)
# customers_num_rows = customers_df.shape[0]
# customers_num_cols = customers_df.shape[1]
# customers_nulls = customers_df.isnull().any(axis=1).sum()  

# results.append({
#             'Table': 'customers',
#             'Num_cols': customers_num_cols,
#             'Num_rows': customers_num_rows,
#             'Nulls': customers_nulls
#         })


for table in tables:
    try:
        # Đọc bảng
        df = pd.read_sql(f'SELECT * FROM {schema}.invalid_int_{table}', engine)

        # Tính toán
        num_rows = df.shape[0]
        num_cols = df.shape[1]
        nulls = df.isnull().any(axis=1).sum()

        results.append({
            'Table': table,
            'Num_cols': num_cols,
            'Num_rows': num_rows,
            'Nulls': nulls
        })
    except Exception as e:
        results.append({
            'Table': table,
            'Num_cols': 'Error',
            'Num_rows': 'Error',
            'Nulls': str(e)
        })

# Chuyển thành DataFrame và hiển thị
summary_df = pd.DataFrame(results)
display(summary_df)

                 Table  Num_cols  Num_rows  Nulls
0               brands         3         0      0
1           categories         3         0      0
2     loyalty_programs         4         0      0
3            suppliers         4         0      0
4             products         9        85      4
5               stores         5         0      0
6            employees         5         0      0
7             payments         5         0      0
8   sales_transactions         8         0      0
9          sales_items         8         0      0
10           inventory         6         0      0
11     stock_movements         7      1942    190
12     purchase_orders         4       210     24
13           shipments         6       565     18
14             returns         4         0      0
15          promotions         5       252      8
16           campaigns         6       286     11
17   customer_feedback         8       483     34
18        store_visits         5      2002    192
19     pricing_history         5      1852    150
20      discount_rules         7       504     19
21           tax_rules         5         0      0

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

# Kết nối tới PostgreSQL
engine = create_engine('postgresql+psycopg2://airflow15:airflow15@localhost:5435/airflow15')

# Danh sách bảng
tables = [
    'brands', 'categories', 'loyalty_programs', 'suppliers', 'products',
    'stores', 'employees', 'payments', 'sales_transactions', 'sales_items', 'inventory',
    'stock_movements', 'purchase_orders', 'shipments', 'returns', 'promotions',
    'campaigns', 'customer_feedback', 'store_visits', 'pricing_history', 'discount_rules',
    'tax_rules'
]

# Schema nếu cần (ví dụ: raw_retails_data)
schema = '_silver_valid_data'

# Danh sách kết quả
results = []

for table in tables:
    try:
        # Đọc bảng
        df = pd.read_sql(f'SELECT * FROM {schema}.int_{table}', engine)

        # Tính toán
        num_rows = df.shape[0]
        num_cols = df.shape[1]
        nulls = df.isnull().any(axis=1).sum()

        results.append({
            'Table': table,
            'Num_cols': num_cols,
            'Num_rows': num_rows,
            'Nulls': nulls
        })
    except Exception as e:
        results.append({
            'Table': table,
            'Num_cols': 'Error',
            'Num_rows': 'Error',
            'Nulls': str(e)
        })

# Chuyển thành DataFrame và hiển thị
summary_df = pd.DataFrame(results)
display(summary_df)

,Table,Num_cols,Num_rows,Nulls
0,brands,2,10,0
1,categories,2,10,0
2,loyalty_programs,3,5,0
3,suppliers,3,10,0
4,products,8,415,0
5,stores,4,20,0
6,employees,4,200,0
7,payments,4,50000,0
8,sales_transactions,7,50000,0
9,sales_items,7,100000,0
10,inventory,5,10000,0
11,stock_movements,6,9029,0
12,purchase_orders,3,895,0
13,shipments,5,435,0
14,returns,3,5000,0
15,promotions,4,248,0
16,campaigns,5,214,0
17,customer_feedback,7,4517,0
18,store_visits,4,8999,0
19,pricing_history,4,9074,0
20,discount_rules,6,496,0
21,tax_rules,Error,Error,(psycopg2.errors.InvalidTextRepresentation) in...

In [5]:
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

# Kết nối tới PostgreSQL
engine = create_engine('postgresql+psycopg2://airflow15:airflow15@localhost:5435/airflow15')

schema = '_silver_valid_data'

# Danh sách kết quả
results = []

customers_df = pd.read_sql(f'SELECT * from {schema}.int_customer_feedback where feedback_id = 1', engine)
display(customers_df)

,feedback_id,customer_id,store_id,product_id,rating,comments,feedback_date
0,1,825,14,325,4,Too expensive,2021-07-26